name: Generate release pull request

on:
  push:
    branches: [ "main" ]

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0

      - name: Prepare release
        uses: labd/changie-release-action@851d6ab1849a152c0aabc79d54e5b0bb85b4f669 # v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-workflow: release.yaml
